
import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";



const metaData = {
  title: "Shehab Movies/Home"
}

const Home: NextPage = () => {
  return (
    <div className="all">
    <Head>
      <title>{metaData.title}</title>
      <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" />
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet" />

    </Head>
      
    <main>
      <div className="home">

        <div className="main">
          <div className="title">
            <h1 className="main-title">Shehab Movies</h1>
            <h2 className="sub-title">
              Enjoy The best <span className="moments">Moments </span>
            </h2>
            <div className="circle"></div>
            <div className="circle-two"></div>
          </div>
          <div className="rocket-div">
            <Image
              src="https://i.postimg.cc/Bb53rCJ6/a9cacd06b96a16a09554d15ef68ad9a7-removebg-preview.png"
              width={400}
              height={400}
              alt="header-img"
              className="rocket"
            />
            <Image src="https://i.postimg.cc/13hfQvrm/istockphoto-1361968232-612x612-removebg-preview.png" width={200} height={200} alt="cloud-img" className="one cloud"/>
            <Image src="https://i.postimg.cc/13hfQvrm/istockphoto-1361968232-612x612-removebg-preview.png" width={200} height={200} alt="cloud-img" className="two cloud"/>
          </div>
        </div>
      
       
      </div>
    </main>
    </div>
  );
};

export default Home;
